[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@solady/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
megaeth_testnet = "https://carrot.megaeth.com/rpc"
megaeth_mainnet = "https://mainnet.megaeth.com/rpc"

[etherscan]
megaeth_testnet = { key = "", url = "https://megaeth-testnet-v2.blockscout.com/api" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
